[project]
name = "jenbot"
version = "1.0.0"
description = ""
authors = [{name = "Warren Davies"}]
homepage = "https://github.com/WarrenDavies/jenbot"
repository = "https://github.com/WarrenDavies/jenbot"
readme = "README.md"
requires-python = ">=3.11,<3.13"
packages = [{include = "jenbot", from = "src"}]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
llama-cpp-python = ">=0.3.16,<0.4.0"
fastapi = {extras = ["standard"], version = "^0.139.2"}
requests = "^2.32.5"
jenerationutils = {path = "../jeneration-utils", develop = true}
speechjenerator = {path = "../speechjenerator", develop = true}
textjenerator = {path = "../text-jenerator", develop = true}
imagejenerator = {path = "../image-jenerator", develop = true}
audiorecorder = {path = "../audio-recorder", develop = true}
sttjenerator = {path = "../stt-jenerator", develop = true}
email-reply-parser = "^0.5.12"
python-dotenv = "^1.2.2"
streamlit = "^1.62.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"