data_connections:
  conversations:
    output_data_type: "csv"
    data_source_location: "./data/conversations.csv"
  messages:
    output_data_type: "csv"
    data_source_location: "./data/messages.csv"
  intent:
    output_data_type: "csv"
    data_source_location: "./data/intent.csv"

bot:
  name: "Jenbot"

user:
  location:
    long: 51.53
    lat: -0.14